### ISSUE TITLE
Observation: When n_objectives > 1, we cannot enter training data as list

### ISSUE THREAD

**Issue by sqbl** [novonordisk-research/ProcessOptimizer#10]
When working with n_objectives > 1, we cannot enter multiple training data-sets as a list.
The easy workaround is to feed the existing data stepwise 
`for i in range(len(X)): 
    opt.tell(X[i], y[i])`

**Comment by AkselObdrup** [comment]
I have looked at this problem and fixed the bug (see pull request above)
