### ISSUE TITLE
Hard to change factor

### ISSUE THREAD

**Issue by MortenSkovsted** [novonordisk-research/ProcessOptimizer#100]
First of all, I do not know if this is possible.

I want to optimize an assay on a liquid handling robot and use this tool to guide the optimization process.

I can make a number of experiments at a time, however only if I don't change some parameters (fx Incubation temperature, incubation time). It would be really valuable if it were possible to set "Hard to change factors" like it is in some DoE experiments.

If this is already a thing and I just don't know about it please correct me, but I think it would be a valuable tool in many cases.

**Comment by sqbl** [comment]
Hi Morten,
Thanks for raising this issue. It is a good and relevant question. Our current solution would be to apply constraints to your optimization. As described [here](https://github.com/novonordisk-research/ProcessOptimizer/blob/develop/examples/constraints.ipynb).
Could that solve your issue?

Best,
Søren

**Comment by MortenSkovsted** [comment]
Hi Søren,
I think the constraints look good for some applications, but unfortunately dos not cover my use case.
The functionality covered in your (very good) examples does not work for me unless I can specify a constant "variable".

I will give an example to illustrate:

I want to optimize output y with:

- Concentration of A from 0 to 1 (x1)
- Incubation temperature 10 to 20 (x2)
- Incubation time 0 to 1 (x3)

The constraints give me the option to set my temperature (x2) to 12.0, to a range 10-15, or to some range of value based on the other variables (x1,x3).

The constraint I would like to set is that x2 can be anything as long as it's the same for the other n experiments.

Unfortunately, none of the constraints can do this.

BR Morten

**Comment by sqbl** [comment]
Hi Morten,

Yes, I see where you are going. And I would love to have a good solution for it. But... 
... I don't.

Theoretically, it should be doable to ask for the best set of next experiments given that one dimension is to be fixed. I.e. the highest learning in one marginalisation of one parameter - and then ask for the marginalisation to perform this in. 
We don't have that feature. But would love to have it. 
For now, how about asking for one experiment and note down the hard to change feature and it's suggested setting. Then either blindly apply this setting in a number of addition new experiments or build a new GPR (optimizer) with all your easy-to-change features, train it on your data, and ask for the last experiments? 
These are hacky solutions, but I guess that their outcomes would not be far inferior to the 'real' solution.
Have a nice weekend
Søren

**Comment by MortenSkovsted** [comment]
Hi Søren,
Thanks for the response and glad you like the idea.
If I could help with the implementation I would definitely help out, but I have a feeling it is not a straightforward task.
Thanks for the hacky solution too, it is definitely better than "losing" the additional test I can do per run.

And at last have a nice weekend
Morten

**Comment by sqbl** [comment]
Closing the issue - but the request for added functionality is not forgotten :-)
