### ISSUE TITLE
Batch-mode optimization: How to choose n>1 new experiments

### ISSUE THREAD

**Issue by sqbl** [novonordisk-research/ProcessOptimizer#132]
Inspired by: https://www.biorxiv.org/content/10.1101/2022.11.12.516271v1, I find it interesting to look further into an optimal way of choosing n>1 new experiments.
Currently, we have implemented "constant_liar" (in a few different flavours), "Kriging Believer" and "Steinerberger sequence"-based ways to get other new experimental recipies than the direct return of the acquisition function.
Inspired by (eq) 5.18 in above paper, I suggest an implementation, where the first of n-new experiments is returned using "EI" as acquisition function with xi at it's user-set setpoint. Then for each new experiment until n is reached, we return an "EI" suggestion with an altered xi. (I would guess that we can increase xi by a factor 5 or 10 between each additional experiment within the current batch)

**Comment by dk-teknologisk-mon** [comment]
It sounds to me like you are asking about a parallel EI function, q-EI where the user is free to choose q? From a bit of searching it seems that people have actually developed this, with one example [here]( https://arxiv.org/abs/1602.05149). An alternative is the parallel knowledge gradient function (q-KG), see [here](https://arxiv.org/abs/1606.04414). This claims to be significantly more robust for systems that contain noise, which is always the case for the data ProcessOptimizer works on.

Both acquisition functions hide inside [this repository](https://github.com/wujian16/Cornell-MOE) from the group that wrote the two above papers. Maybe we could extract them into PO?
