### ISSUE TITLE
Multiobjective mode: Document the model used for suggesting the next experiment

### ISSUE THREAD

**Issue by dk-teknologisk-cbb** [novonordisk-research/ProcessOptimizer#134]
In multiobjective mode (n_objectives > 1), the next experiment is chosen differently than in single objective mode. This needs to the documented in some way, possibly through examples. 
The choice of the next experiment in multiobjective mode is not deterministic. Investigate whether this is good enough, and add an explanation in an example.

**Comment by SRFU-NN** [comment]
Fixed in #279
