### ISSUE TITLE
Expand the number of benchmark functions and ModelSystems

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [novonordisk-research/ProcessOptimizer#135]
In order to facilitate future benchmarking studies (relevant to issues #13, #76, #121, #131 and #132) it would help to expand the set of benchmark functions we have. At first glance, there is plenty of inspiration to find on the [website](http://www.sfu.ca/~ssurjano/optimization.html) we link to for the benchmark functions we have already implemented. The problem is that most of these functions do not have what I would term "realistic" structure for physical systems, usually because of strongly oscillating values and/or very shallow minima compared to the overall landscape. 

After looking through a lot of options, I have found some that do not suffer as strongly from this problem:
- [Himmelblau's function](https://en.wikipedia.org/wiki/Himmelblau%27s_function) (2D), to represent a system that features several viable solutions. If we implement it as the log-value it would make the valleys between viable options substantially "deeper".
- [Rosenbrock function](https://en.wikipedia.org/wiki/Rosenbrock_function) (any D), to represent a widely dispersed solution that follows a curved shape (in practical applications, the tiny global minimum is irrelevant).
- [Ackley function](http://www.sfu.ca/~ssurjano/ackley.html) (any D), to represent a narrow solution in a sea of local minima.
- [Easom function](http://www.sfu.ca/~ssurjano/easom.html) (2D), to represent the "golf hole" scenario of a very local solution surrounded by a large area of flatness (depending on the allowed domain).
- [Peaks function from MATLAB](https://se.mathworks.com/help/matlab/ref/peaks.html) (2D), an interesting function that contains really "bad" solutions in close proximity to the good solutions, while all points along the edges of the domain are average.
- Look-up tables of fully mapped real systems. This category is in itself very interesting, but requires scouring the literature as such data is rare. One example could be to extract the fully mapped synthesis data from [this paper](https://www.nature.com/articles/s41586-021-03213-y).

Additional suggestions would be _very_ welcome.

**Comment by sqbl** [comment]
This might be worth looking at: https://iopscience.iop.org/article/10.1088/2632-2153/abedc8

**Comment by sqbl** [comment]
More real world data is gathered here: https://docs.open-reaction-database.org/en/latest/
As described here: https://pubs.acs.org/doi/10.1021/jacs.1c09820

**Comment by sqbl** [comment]
Remember to add test cases that reflects pareto optimizations
