### ISSUE TITLE
Random value sampling is broken for integers

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [novonordisk-research/ProcessOptimizer#158]
When drawing initial data points for a space that includes integer values, you expect a fairly even distribution of settings across the levels of the integer dimension. In other words, if a factor A has levels [0, 1, 2] and you draw 3000 points, you expect about 1000ish occurrences of 0, 1000ish of 1 etc. 

If I build an optimizer with the space `dimensions = [(-3.0, 3.0), (-2.0, 2.0), (-3.0, 3.0), (0, 2)]` and ask for 1000 initial points and then look at the settings of the last dimension I get about 250 0's, 500 1's and 250 2's. If I build it with the limits (0, 4), and do one draw of 1000 points I get [108, 241, 258, 240, 153] occurrences of [0, 1, 2, 3, 4]. 

This to me looks like there is some rounding going on that shouldn't be used, but a very quick glance at the rvs-methods of the Integer class inside the space.py file doesn't look like it explains the above.

**Comment by sqbl** [comment]
I can reproduce the error. It seems persistent even if you have `lhs=True` (default) or `lhs=False`. I'll look further into it. Could it be part of the transform/reverse_transform code?

**Comment by sqbl** [comment]
Next clue, If we run with f.x. `base_estimator='ET'` is does not seem to give strange distributions (neither for `'GBRT'` or `'Dummy'`). In optimizer.py line 285, it appears that space is "normalized" when we use `'GP'`.

**Comment by sqbl** [comment]
Reason found: transformers.py line 141.
During inverse_transform, if the input is `integer`, the inversed_X ("the x that has been in the normalized space and has now returned to the human world...") is rounded before being returned to the user. This is not the case if the input is `real`. If I run [0.01, 0.02, ..., 1.0] thorugh the inverse_transform method of an `integer` dimension, the resulting histogram shows low amounts of "low" and "high" members (perhaps expected, but unwanted effect):
![image](https://user-images.githubusercontent.com/39369016/228848563-225e899d-2c4d-4340-bf4d-200080cec59d.png)
(sorry for ugly formatting).

Now, we only need to find a better way of inversely transforming the rng-numbers back into human world evenly. That code should go to line 141 and everything will be fine... (famous last words...)

**Comment by sqbl** [comment]
(Need to tell that the above dimension is `Integer(0,5)`.
0.01-0.10 translates into a number that is rounded to 0,
0.11-0.29 translates to 1,
...
0.91-1.0 translates to 5

**Comment by sqbl** [comment]
Steps towards a solution (still up for discussion upon further investigations):
transformers.py line 142: `np.round` -> `np.floor` 
#this will solve the issue with the lower value in the Integer-range being under-represented. But now "only" 1.0 (in normalized-space) will translate into the higher value in the Integer-range. To have this solved, we can "hack" the transformer:
space.py line 376: `high` -> `high +1`.
#The question is if this is stable enough or too much of a short-term hack? 

edit1: In principle, we can now return a value that is 1 more than the user given input range. That is surely not optimal. and should be checked for to avoid.

edit2: perhaps just add 0.9999 to high

**Comment by SRFU-NN** [comment]
> nsformers.py line 142: np.round -> np.floor
#this will solve the issue with the lower value in the Integer-range being under-represented. But now "only" 1.0 (in normalized-space) will translate into the higher value in the Integer-range. To have this solved, we can "hack" the transformer:
space.py line 376: high -> high +1.

As best I can tell, this solution has two issues.

Firstly, we have points in transformed space where the closest valid point is not the point they are reverse transformed to. If we assume the integers go from 1 to 4, the will be tranformed according to {1: 0, 2: 0.25, 3: 0.5, 4: 0.75}. Now, 0.24 is very close to 0.25, which is the "canonical" representation of 2, but it will be reverse transformed to 1.

If the optimal point is 0.24, 0.25 is probably a better value than 0. However, this approach will suggest 1 if the optimal point of the surrogate function is just below 2.

Secondly, the end points aren't treated identically. For the highest value, the area that represents in in transformed space is not bordered by another value. I think this means that the area that represents it will have a higher uncertainty. This might "fool" the acquisition function to sample it too often. This is less of a problem.

I would suggest modifying line 376 to
```
            self.transformer = Normalize(low-0.5, high+0.5, is_int=True)
```

That way (I think), reverse_transform will always return the nearest integer.

**Comment by dk-teknologisk-mon** [comment]
The issue also lives within the latin hypercube sampling code for Integer dimensions as well. Implementing the suggested change in line 376 of space.py does not fix the issue for initial points in this code:
```python
from ProcessOptimizer import Optimizer

space = [(-1.0, 1.0), (1, 5)]
# Build optimizer
opt = Optimizer(
    dimensions=space,
    lhs=True,
    acq_func="EI",
    n_initial_points=1000,
    random_state=42,
)
x = opt.ask(1000)
```
However, if I change line 441 `samples = (np.arange(n)+0.5)/n` to `samples = randint.rvs(self.low, self.high + 1, size=n)`, and just return these samples then LHS provides evenly many values of the allowed integers during the initial sampling. _However_, these initial points are no longer reproducible, because they are not seeded.

Before implementing the solution to this, I guess we need to talk about how we want to handle the cases where the user asks for a "low" number of initial points compared to the number of levels in the integer dimension. E.g. if `dimension = (0, 10)` and `n_initial_points=5`, which five values do we then wish to give? Random values is not really in the "spirit" of LHS, but what is? The first N values (0, 1, 2, 3, 4) also seems non-sensical, so perhaps we should "pop" values from the list of allowed levels up to N, and then repeat if `N>number_of_levels`?

**Comment by SRFU-NN** [comment]
We want at least the following properties for an integer dimension:

- We want random sampling to be a flat distribution in transformed space.
- Every possible value should have equal probability of being randomly sampled.
- A point in transformed space should be reverse transformed to the nearest "canonical value". That is, if the integer values `I1, I2, I3, ... , In` are transformed into `T1, T2, T3, ... , Tn`, for all `x` in the transformed space, where `reverse_transform(x) = Ix`, we want `|x-transform(Ix)|<=|x-transform(In)|` for all n.
- We want the Gaussian process to treat all of the subsets of the transformed space that map to a certain integer "identically". in particular, we want them to be equally "bordered" by "canonical values" (this isn't super clearly descirved, I will try to exemplify further).

We can't have all of these conditions met, so the question is which to compromise on.

Here follows sketches of the transformed space of the different possible solutions with four integer values. `|` represents borders between subsets that map to different integers with `reverse_transform`. `-` and `*` represents equal parts of the transformed space, with `*` representing "canonical values", that is, `transform(I)` for some integer `I`.

**As it is today**
`|*-|--*-|--*-|-*|`
(the middle two "canonical values" should be in the middle of their subsets)

The two subsets in the ends are smaller than the rest, leading to unequal random sampling

**Using `floor`**
`|*---|*---|*---|*---|`

The values at the high end of the subsets are closer to a "canonical value" that is not in their subset. Also, the last subset to has all of its range "outside" the values that can be sampled. This will lead to the estimated uncertainty being bigger in parts of this subset.

This is a mirror image of using `ceil`, so I will not show that option.

**using `round`**
`|-*--|-*--|-*--|-*--|`
(all "canonical values" should be in the middle of their subsets)

This seems like the best solution. The only issue is that the two extreme subsets have parts "outside" of the values that can be samples, which leads to the estimated uncertainty being bigger in parts of these subset.

**Comment by SRFU-NN** [comment]
With regard to LHS, I feel like we should give `reverse_transform` of LHS of the continuous transformed space. So if the user wants fewer initial points than there are integers, we equally distribute the initial points over the range.
