### ISSUE TITLE
Noise models cannot be seeded for reproducibility

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [novonordisk-research/ProcessOptimizer#159]
The newly added ModelSystem class is super nice, but I think we have overlooked an essential feature in the NoiseModel subclass, namely a consistent way of seeding it to ensure reproducible tests and benchmarks.

@SRFU-NN you're the rather obvious person to have an opinion on how to go about doing this?

**Comment by dk-teknologisk-mon** [comment]
An important note for this issue is that since the code-base was originally made, NumPy has changed its convention for how to generate random numbers and seed them, [see here.](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator) Their change should make it fairly easy to ensure consistency by providing an optional keyword argument ala `seed=42`.

**Comment by SRFU-NN** [comment]
Good point. I use the old way of seeding (`np.random.seed(42)`, which is officially discouraged, and definitely shouldn't be used in modules), so I will have to read up on how to do it correctly.

We would like to be able to reset the random seed, right? So you can do an optimisation, change the code, and do the same optimisation? That would be nice if we are optimising CPU efficiency, but otherwise you might as well make a new ModelSystem (I think). But it will make the code slightly more complicated.

**Comment by SRFU-NN** [comment]
I have two other thing I would like to do with the ModelSystem, [more flexibility for score function](https://github.com/novonordisk-research/ProcessOptimizer/discussions/156) and [checking whether points are in the space and dynamically handle it](https://github.com/novonordisk-research/ProcessOptimizer/discussions/155). I am not sure whether the best approach is one big pull request, or three smaller ones.

Edit: We have decided to make pull requests covering one issue, so this will be three separate pull requests.

**Comment by SRFU-NN** [comment]
Documentation for how to use the numpy random with seed:

https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.default_rng

**Comment by dk-teknologisk-mon** [comment]
Based on the numpy Generator structure, I think the best solution will be to build such a generator into the ModelSystem object at initialization with something like:

```python
def __init__(
    self,
    noise_size: Optional[float],
    seed: Union[int, None] = 42,
):
if seed != None:
    self._rng = np.random.default_rng(seed)
else:
    self._rng = np.random.default_rng()
```

If I understand the generator structure correctly, this should mean that when we wish to sample our noise, we can do something like this:
```python
def set_noise_type(self,noise_type: str):
        if noise_type in ["normal", "Gaussian", "norm"]:
            self._noise_distribution = self._rng.normal
        elif noise_type == "uniform":
            self._noise_distribution = self._rng.uniform(low=-1, high=1)
        else:
            raise ValueError(f"Noise distribution \"{noise_type}\" not recognised.")
```
If we're lucky, this relatively small change would implement seeding as a default and decouple the advancement of the noise rng from all other random number sampling in the code.

I'm presently building this implementation as part of adding more benchmarks, and will test that the above works as I think it does.
