### ISSUE TITLE
Fix numpy deprecation warnings

### ISSUE THREAD

**Issue by SRFU-NN** [novonordisk-research/ProcessOptimizer#163]
We use a few numpy calls that are deprecated, it should be fixed.

ProcessOptimizer/tests/test_constraints.py::test_SumEquals
ProcessOptimizer/tests/test_constraints.py::test_SumEquals
  C:\Users\srfu\MATLAB\Projects\ProcessOptimizer\ProcessOptimizer\space\constraints.py:832: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
    low_limit_sum = np.sum(space.bounds[dim][0] for dim in constraint.dimensions)

ProcessOptimizer/tests/test_constraints.py::test_SumEquals
ProcessOptimizer/tests/test_constraints.py::test_SumEquals
  C:\Users\srfu\MATLAB\Projects\ProcessOptimizer\ProcessOptimizer\space\constraints.py:837: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
    high_limit_sum = np.sum(space.bounds[dim][1] for dim in constraint.dimensions)

ProcessOptimizer/tests/test_constraints.py::test_SumEquals
ProcessOptimizer/tests/test_constraints.py::test_SumEquals
  C:\Users\srfu\MATLAB\Projects\ProcessOptimizer\ProcessOptimizer\space\constraints.py:189: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    N = matrix(np.ones(d))

**Comment by sqbl** [comment]
Seems to have been fixed by #185. Therefore, I close it. Feel free to reopen
