### ISSUE TITLE
Version 0.8.2 can not be imported

### ISSUE THREAD

**Issue by SRFU-NN** [novonordisk-research/ProcessOptimizer#198]
src/utils are not packaged, fix in setup.py

**Comment by SRFU-NN** [comment]
While fixing it, I am also introducing testing in python 3.11. There seems to be a problem with installing scipy here. I will investigate further next week.

**Comment by SRFU-NN** [comment]
The problem is only there with the BB install. It might be due to an old version of something not supporting python 3.11

**Comment by sqbl** [comment]
Closed by #201
