### ISSUE TITLE
noise_size could raise an error when noise_model is ZeroNoise

### ISSUE THREAD

**Issue by sqbl** [novonordisk-research/ProcessOptimizer#262]
Currently, the package will happily let you set a noise_size, when the underlaying noisemodel is ZeroNoise. This can lead to confusion for the users. One example could be, when users start with the branin_no_noise modelsystem and experiment with adding noise. To avoid discussions on what a "default" noise could/should be, I suggest that we simply assert that noise is not zernoise, when the user tries to set a noise size.

**Comment by sqbl** [comment]
Some additional observations/issues:

- Open examples/model systems.ipynb [exchange all "branin_hoo" with "branin_no_noise"]
- Run cell [1]
- change "branin_no_noise.noise_size" in cell [2]. No changes observed. (This is the **_main issue_**/non-intended behaviour in this present Github issue)
- Run cell [3], observed noise
- Revisit cell [2], now noise is shown (as expected)
- Replace "branin_no_noise" with "branin"
- Run cell [1], observe **_expected_** noise
- Replace "branin" with "branin_no_noise"
- Run cell [1], observe **_unexpected_** noise.

I believe the "memory effect" on the previously instantiated noisy model has to do with the way modelsystems are build. Perhaps they are functions that does not get re-imported due to pythons laziness/smartness(?) 
Can we force a reinstantiation of a modelsystem, when it is imported? Or code them as classes to ensure that a new instance doesn't have a memory?

Related, the present example is importing branin_hoo, which has since been replaced with branin and branin_no_noise in the repo. Import of branin_hoo should fail.

**Comment by SRFU-NN** [comment]
> Currently, the package will happily let you set a noise_size, when the underlaying noisemodel is ZeroNoise. This can lead to confusion for the users. One example could be, when users start with the branin_no_noise modelsystem and experiment with adding noise. To avoid discussions on what a "default" noise could/should be, I suggest that we simply assert that noise is not zernoise, when the user tries to set a noise size.

Fixed in #264
