### ISSUE TITLE
second_order_polynomial_2d.py

### ISSUE THREAD

**Issue by sqbl** [novonordisk-research/ProcessOptimizer#268]
I believe that "second_order_polynomial_2d.py" (in model systems) will try to import poly_2d from the benchmarks.py file. Yet, poly_2d is not contained in that file.

**Comment by SRFU-NN** [comment]
You are ight, and I had missed that entire file in my modelsystem update PR. 

It has been renamed to poly2, so I will just delete the file `second_order_polynomial_2d.py` in my PR.

**Comment by SRFU-NN** [comment]
Fixed in #265
