### ISSUE TITLE
Warning, this point has been tried before

### ISSUE THREAD

**Issue by sqbl** [novonordisk-research/ProcessOptimizer#288]
This warning is deemed to be wrong.
We would like to have a two step approach to solve it:
First: change the wording in the warning to explain to the user that the regresser found reason to repeat the experiment
Secondly: move the formalism to the upcoming Director class. Here, we would expect the director to know if the user wants to repeat experiments or not.

**Comment by sqbl** [comment]
![image](https://github.com/user-attachments/assets/c0d2a435-b7a0-48df-bdd0-6f308195b481)

**Comment by RuneChristensen-NN** [comment]
On it
