### ISSUE TITLE
LHS sampling is different if limits are continuous or discrete

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [novonordisk-research/ProcessOptimizer#88]
The points returned by the latin hypercube sampling differs, depending on whether the min/max limits are defined as integers or reals. An example that illustrates it is the following code:

```
from ProcessOptimizer import Optimizer
n_init = 5
space1 = [(0,100),(0,100),(0,100)]
space2 = [(0.0,100.0),(0.0,100.0),(0.0,100.0)]
opt1 = Optimizer(space1,n_initial_points=n_init)
opt2 = Optimizer(space2,n_initial_points=n_init)
opt1.ask(5)
opt2.ask(5)
```

op1 returns:
```[[25, 75, 0], [100, 50, 50], [50, 25, 25], [0, 0, 75], [75, 100, 100]]```
while opt2 returns:
```[[30.0, 70.0, 10.0], [90.0, 50.0, 50.0], [50.0, 30.0, 30.0], [10.0, 10.0, 70.0], [70.0, 90.0, 90.0]]```

In my opinion, these lists should be the same within rounding. The difference is caused by different definitions of `lhs_arange` for the class Real and the class Integer in space.py. In the case of Real the points are spaced equally, with a half-step buffer to the limit values like this:  `a = (np.arange(n)+0.5)/n`, while Integers do not include the buffer at the limits: `rounded_numbers = np.round(np.linspace(self.low, self.high, n))`.

I'll work on a fix for the integer class.

**Comment by sqbl** [comment]
Hi Morten, 
Well spotted! And clearly a bug that will be nice to have fixed.
Would it be another alternative solution to do the LH-sampling in "transformed x-space" and then rely on correct re-transformation back into "human-space"?
Among the possible solutions to the issue, I like the ones that return points, which are not at the extremes of the dimensions (i.e. like your opt2 above). 
Let me know, if you need help in coding something
/S
