### ISSUE TITLE
Speed-up of convergence/metrics plotting

### ISSUE THREAD

**Issue by dk-teknologisk-rtfh** [novonordisk-research/ProcessOptimizer#94]
Right now plot_expected_minimum_convergence needs to "replay" the full optimization for plotting convergence plots.
The information of the current model status through an optimization process is needed for the  extraction of the expected minima + uncertainties.
The necessary information could also be extracted from the models attribute within the optimizer object which is extended on each call of tell(). Right now expected_minimum() only uses the latest model from said models attribute.
Therefore expected_minimum() could be adapted accordingly or a separate helper function could be introduced.

I see that this approach fails as soon as multiple points at once are used within tell(). For this case one could think of storing information about how many points were handed over to tell() and only replay optimizations for the cases where it is necessary.

**Comment by sqbl** [comment]
It is a good point and a much needed optimization of compute-time for that particular plot. A solution to the issue with parallel data reporting ("batch-type" optimizations) could be to extract the number of training points progressively from each model and then make the plot_expected_minimum_convergence to plot with the granularity given from the frequency of data inputs.
